Repository milvus-io/milvus-helm, pull requests merged in 2021-08, with the labels that each got.

#202 Upgrade ETCD helm chart version to 6.3.3
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/charts/etcd-5.5.0.tgz
  charts/milvus/charts/etcd-6.3.3.tgz
  charts/milvus/requirements.lock
  charts/milvus/requirements.yaml
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#205 Bumped milvus verison to v2.0.0-rc.3
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#206 Bumped milvus verison to 2.0.0-rc.4
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#208 add flags to log output on stdout & disk
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/_server_config.tpl
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#209 merge all milvus servicemonitors into one.
  charts/milvus/Chart.yaml
  charts/milvus/templates/servicemonitor.yaml
Labels: lgtm, approved, size/L

#213 Bumped milvus verison to 2.0.0-rc.5
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/pulsar-standalone-deployment.yaml
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#214 [skip ci] Closes abandoned issues after a period of inactivity
  .github/stale.yml
Labels: lgtm, size/S, approved

#215 [skip ci] Upgrade Minio helm chart version to 8.0.10
  charts/milvus/Chart.yaml
  charts/milvus/charts/minio-8.0.10.tgz
  charts/milvus/charts/minio-8.0.9.tgz
  charts/milvus/requirements.lock
  charts/milvus/requirements.yaml
Labels: lgtm, size/S, approved

#216 Upgrade pulsar standalone image version to 2.7.3
  charts/milvus/Chart.yaml
  charts/milvus/templates/pulsar-standalone-deployment.yaml
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved
