Repository milvus-io/milvus-helm, pull requests merged in 2021-07, with the labels that each got.

#186 [skip ci] Add example of expanding a Milvus cluster
  charts/milvus/README.md
Labels: size/S

#187 [skip ci] Modified Milvus Helm chart description
  charts/milvus/Chart.yaml
Labels: size/XS

#191 Add Pulsar standalone data persistence volumes
  .github/workflows/lint-test.yml
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/config.tpl
  charts/milvus/templates/datacoord-deployment.yaml
  charts/milvus/templates/datanode-deployment.yaml
  charts/milvus/templates/indexcoord-deployment.yaml
  charts/milvus/templates/indexnode-deployment.yaml
  charts/milvus/templates/proxy-deployment.yaml
  charts/milvus/templates/pulsar-standalone-deployment.yaml
  charts/milvus/templates/pvc.yaml
  charts/milvus/templates/querycoord-deployment.yaml
  charts/milvus/templates/querynode-deployment.yaml
  charts/milvus/templates/rootcoord-deployment.yaml
  charts/milvus/templates/standalone-deployment.yaml
  charts/milvus/values.yaml
Labels: approved, size/L

#192 Set pulsar defaultRetentionTimeInMinutes parameter to 10080
  charts/milvus/Chart.yaml
  charts/milvus/templates/pulsar-standalone-deployment.yaml
Labels: approved, lgtm, size/XS

#193 Expose the bucketName configuration parameter
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: approved, lgtm, size/M

#194 HorizontalPodAutoscaler support
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/hpa.yaml
  charts/milvus/values.yaml
Labels: approved, lgtm, size/L

#195 Bumped milvus verison to 2.0.0-rc.2
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: approved, lgtm, size/XS

#196 Expose root of key prefix to etcd configuration
  .github/workflows/checks.yaml
  .github/workflows/markdown.links.config.json
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: approved, lgtm, size/M

#197 Add retention time and retention size of rocksmq
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: approved, lgtm, size/S

#198 Update REAMDE.md for service monitor
  charts/milvus/README.md
Labels: approved, lgtm, size/XS

#199 Add Milvus logs data persistence volumes
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/config.tpl
  charts/milvus/templates/datacoord-deployment.yaml
  charts/milvus/templates/datanode-deployment.yaml
  charts/milvus/templates/indexcoord-deployment.yaml
  charts/milvus/templates/indexnode-deployment.yaml
  charts/milvus/templates/proxy-deployment.yaml
  charts/milvus/templates/pvc.yaml
  charts/milvus/templates/querycoord-deployment.yaml
  charts/milvus/templates/querynode-deployment.yaml
  charts/milvus/templates/rootcoord-deployment.yaml
  charts/milvus/templates/standalone-deployment.yaml
  charts/milvus/values.yaml
Labels: approved, lgtm, size/L

#200 Change the mount path of Milvus logs persistence volume
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: approved, lgtm, size/XS
