Repository milvus-io/milvus-helm, pull requests merged in 2021-12, with the labels that each got.

#263 Fix minio and pulsar config when release name contains minio or pulsar
  charts/milvus/Chart.yaml
  charts/milvus/templates/config.tpl
Labels: lgtm, size/S, approved

#264 Add strategy config for coordinator
  charts/milvus/Chart.yaml
  charts/milvus/templates/datacoord-deployment.yaml
  charts/milvus/templates/indexcoord-deployment.yaml
  charts/milvus/templates/querycoord-deployment.yaml
  charts/milvus/templates/rootcoord-deployment.yaml
Labels: lgtm, size/S, approved

#266 Set pulsar backlog quota to 8G
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#267 enable autoBalance for queryCoordinator
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#268 change config for dataCoordinator
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#269 Fix the problem of ingress version mismatch
  charts/milvus/Chart.yaml
  charts/milvus/templates/ingress.yaml
  charts/milvus/templates/insight-ingress.yaml
Labels: lgtm, approved, size/L

#270 modify the interval time for monitor
  charts/milvus/Chart.yaml
  charts/milvus/templates/servicemonitor.yaml
Labels: size/XS, lgtm, approved

#271 Add parameters compaction for dataCoord
  charts/milvus/Chart.yaml
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#272 Change config maxFieldNum for proxy
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#273 Keep minio pvc for milvus standalone
  charts/milvus/Chart.yaml
  charts/minio/Chart.yaml
  charts/minio/values.yaml
Labels: size/XS, lgtm, approved

#274 Upgrade minio chart version to 8.0.11
  charts/milvus/Chart.yaml
  charts/milvus/charts/minio-8.0.10.tgz
  charts/milvus/charts/minio-8.0.11.tgz
  charts/milvus/requirements.lock
  charts/milvus/requirements.yaml
Labels: lgtm, size/S, approved

#275 Add GODEBUG env to release memory
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: lgtm, size/M, approved

#277 Add podMonitor for pulsar broker and proxy
  charts/milvus/Chart.yaml
  charts/milvus/templates/_helpers.tpl
  charts/milvus/templates/pulsar-podmonitor.yaml
  charts/milvus/values.yaml
Labels: lgtm, size/M, approved

#280 Bump milvus version to 2.0.0-pre-ga
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
  charts/minio/Chart.yaml
  charts/minio/README.md
Labels: size/S, approved
