Repository milvus-io/milvus-helm, pull requests merged in 2021-06, with the labels that each got.

#178 Fix the link for Milvus logo in Chart.yaml
  charts/milvus/Chart.yaml
Labels: size/XS

#179 Upgrade Milvus version to 1.1.1
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: size/S

#180 feature: add s3 storage support
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/_readonly_server_config.tpl
  charts/milvus/templates/_server_config.tpl
  charts/milvus/templates/pvc.yaml
  charts/milvus/templates/readonly-deployment.yaml
  charts/milvus/templates/writable-deployment.yaml
  charts/milvus/values.yaml
Labels: size/M

#185 Fix milvus worker node name bug
  charts/milvus/Chart.yaml
  charts/milvus/templates/_helpers.tpl
  charts/milvus/templates/datanode-deployment.yaml
  charts/milvus/templates/datanode-svc.yaml
  charts/milvus/templates/indexnode-deployment.yaml
  charts/milvus/templates/indexnode-svc.yaml
  charts/milvus/templates/querynode-deployment.yaml
  charts/milvus/templates/querynode-svc.yaml
  charts/milvus/templates/servicemonitor.yaml
  charts/milvus/values.yaml
Labels: size/M
