Repository milvus-io/milvus-helm, pull requests merged in 2021-09, with the labels that each got.

#217 Add minio helm chart
  .github/workflows/lint-test.yml
  .github/workflows/release.yml
  charts/minio/.helmignore
  charts/minio/Chart.yaml
  charts/minio/README.md
  charts/minio/templates/NOTES.txt
  charts/minio/templates/_helper_create_bucket.txt
  charts/minio/templates/_helpers.tpl
  charts/minio/templates/clusterroles.yaml
  charts/minio/templates/configmap.yaml
  charts/minio/templates/deployment.yaml
  charts/minio/templates/ingress.yaml
  charts/minio/templates/networkpolicy.yaml
  charts/minio/templates/poddisruptionbudget.yaml
  charts/minio/templates/post-install-create-bucket-job.yaml
  charts/minio/templates/post-install-prometheus-metrics-job.yaml
  charts/minio/templates/post-install-prometheus-metrics-role.yaml
  charts/minio/templates/post-install-prometheus-metrics-rolebinding.yaml
  charts/minio/templates/post-install-prometheus-metrics-serviceaccount.yaml
  charts/minio/templates/pvc.yaml
  charts/minio/templates/rolebindings.yaml
  charts/minio/templates/secrets.yaml
  charts/minio/templates/securitycontextconstraints.yaml
  charts/minio/templates/service.yaml
  charts/minio/templates/serviceaccount.yaml
  charts/minio/templates/servicemonitor.yaml
  charts/minio/templates/statefulset.yaml
  charts/minio/values.yaml
  ct.yaml
Labels: lgtm, size/XXL, approved

#218 Upgrade minio helm chart to 8.0.10
  .github/workflows/lint-test.yml
  charts/milvus/.helmignore
  charts/milvus/Chart.yaml
  charts/milvus/charts/minio-8.0.10.tgz
  charts/milvus/ci/cluster-values.yaml
  charts/milvus/requirements.lock
  charts/milvus/requirements.yaml
Labels: lgtm, size/M, approved

#219 Fix release milvus helm chart bug
  .github/workflows/release.yml
Labels: size/XS, lgtm, approved

#220 Bumped milvus verison to 2.0.0-rc.5-hotfix1
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#221 Fix 2.0.0-rc5-hotfix1 image tag
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#210 Add minIO GCS gateway support
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#222 [skip ci] Update .gitignore
  .gitignore
  charts/milvus/templates/config.tpl
Labels: lgtm, size/S, approved

#223 Increase pulsar storage size
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#224 Increase the default pulsar pvc storage to 100GB
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#225 Set milvus standalone upgrade strategy to recreate
  charts/milvus/Chart.yaml
  charts/milvus/templates/standalone-deployment.yaml
Labels: size/XS, lgtm, approved

#226 Bumped milvus verison to 2.0.0-rc.6
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#230 Enable etcd auto compaction by revision
  OWNERS
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#232 Add msgChannel config to milvus.yaml
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: lgtm, size/M, approved

#233 Add CACHE_SIZE env to milvus components
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: lgtm, size/M, approved

#234 Add CACHE_SIZE env to milvus components deployments
  charts/milvus/Chart.yaml
  charts/milvus/templates/datacoord-deployment.yaml
  charts/milvus/templates/datanode-deployment.yaml
  charts/milvus/templates/indexcoord-deployment.yaml
  charts/milvus/templates/indexnode-deployment.yaml
  charts/milvus/templates/proxy-deployment.yaml
  charts/milvus/templates/querycoord-deployment.yaml
  charts/milvus/templates/querynode-deployment.yaml
  charts/milvus/templates/rootcoord-deployment.yaml
  charts/milvus/templates/standalone-deployment.yaml
  charts/milvus/values.yaml
Labels: lgtm, approved, size/L

#235 Fix milvus template with CACHE_SIZE env
  charts/milvus/Chart.yaml
  charts/milvus/templates/datacoord-deployment.yaml
  charts/milvus/templates/datanode-deployment.yaml
  charts/milvus/templates/indexcoord-deployment.yaml
  charts/milvus/templates/indexnode-deployment.yaml
  charts/milvus/templates/querycoord-deployment.yaml
  charts/milvus/templates/querynode-deployment.yaml
  charts/milvus/templates/rootcoord-deployment.yaml
  charts/milvus/templates/standalone-deployment.yaml
Labels: lgtm, approved, size/L

#236 Fix milvus template
  charts/milvus/Chart.yaml
  charts/milvus/templates/datacoord-deployment.yaml
  charts/milvus/templates/datanode-deployment.yaml
  charts/milvus/templates/indexcoord-deployment.yaml
  charts/milvus/templates/indexnode-deployment.yaml
  charts/milvus/templates/querycoord-deployment.yaml
  charts/milvus/templates/querynode-deployment.yaml
  charts/milvus/templates/rootcoord-deployment.yaml
Labels: lgtm, size/M, approved

#231 Enable milvus cluster by default along with dependencies
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/ci/cluster-values.yaml
  charts/milvus/templates/config.tpl
  charts/milvus/templates/pulsar-standalone-deployment.yaml
  charts/milvus/templates/pulsar-standalone-svc.yaml
  charts/milvus/templates/pvc.yaml
  charts/milvus/values.yaml
  ct.yaml
Labels: lgtm, approved, size/L
