Repository milvus-io/milvus-helm, pull requests merged in 2021-11, with the labels that each got.

#245 Bump milvus version to 2.0.0-rc.8
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#246 Add rocksmq page size config
  charts/milvus/Chart.yaml
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#247 Add config root coord delta channel prefix
  charts/milvus/Chart.yaml
  charts/milvus/templates/config.tpl
Labels: size/XS, lgtm, approved

#248 Bump milvus version to v2.0.0-rc8-20211104-d1f4106
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#250 Set autoBalance config to false
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#251 Set retention size to 8GB and retention time to 7 days
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#252 Add more milvus config
  charts/milvus/Chart.yaml
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: lgtm, approved, size/L

#239 Add health check for milvus components
  charts/milvus/Chart.yaml
  charts/milvus/templates/datacoord-deployment.yaml
  charts/milvus/templates/datanode-deployment.yaml
  charts/milvus/templates/indexcoord-deployment.yaml
  charts/milvus/templates/indexnode-deployment.yaml
  charts/milvus/templates/proxy-deployment.yaml
  charts/milvus/templates/querycoord-deployment.yaml
  charts/milvus/templates/querynode-deployment.yaml
  charts/milvus/templates/rootcoord-deployment.yaml
  charts/milvus/templates/standalone-deployment.yaml
  charts/milvus/values.yaml
Labels: lgtm, approved, size/L

#253 Enable compaction for data coordinator by default
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#254 Disable data coordinator compaction by default
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#256 Add gc config for data coordinator
  charts/milvus/Chart.yaml
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#257 Enable compaction for data coordinator
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#259 Fix milvus etcd config when release name contains etcd
  charts/milvus/Chart.yaml
  charts/milvus/templates/config.tpl
  ct.yaml
Labels: size/XS, lgtm, approved

#258 Add insight to Milvus helm
  charts/milvus/Chart.yaml
  charts/milvus/templates/_helpers.tpl
  charts/milvus/templates/insight-deployment.yaml
  charts/milvus/templates/insight-ingress.yaml
  charts/milvus/templates/insight-svc.yaml
  charts/milvus/values.yaml
Labels: lgtm, approved, size/L

#260 Refine memory settings for pulsar components
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#261 Add rootPath config for minio
  charts/milvus/Chart.yaml
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#262 change bookkeeper replicas for pulsar
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved
