Repository milvus-io/milvus-helm, pull requests merged in 2022-11, with the labels that each got.

#383 Change params for values.yaml
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#384 Enable disk index by default
  .github/workflows/markdown.links.config.json
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#387 Add parameter threadCoreCoefficient (#386)
  charts/milvus/Chart.yaml
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#388 Fix invalid yaml comment
  charts/milvus/Chart.yaml
  charts/milvus/templates/config.tpl
Labels: size/XS, lgtm, approved

#391 Bump milvus version to 2.2.0
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: lgtm, size/M, approved

#392 Change default log level to info
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved
