Repository milvus-io/milvus-helm, pull requests merged in 2022-10, with the labels that each got.

#375 modify quotaAndLimits params
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: lgtm, size/M, approved

#364 Milvus - Add / Customize Service Account
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/_helpers.tpl
  charts/milvus/templates/datacoord-deployment.yaml
  charts/milvus/templates/datanode-deployment.yaml
  charts/milvus/templates/indexcoord-deployment.yaml
  charts/milvus/templates/indexnode-deployment.yaml
  charts/milvus/templates/proxy-deployment.yaml
  charts/milvus/templates/querycoord-deployment.yaml
  charts/milvus/templates/querynode-deployment.yaml
  charts/milvus/templates/rootcoord-deployment.yaml
  charts/milvus/templates/serviceaccount.yaml
  charts/milvus/templates/standalone-deployment.yaml
  charts/milvus/values.yaml
Labels: lgtm, size/M, approved

#376 Refine data coordinator segment config
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#378 Enable quota and limits in helm
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#379 Add local storage size limit
  charts/milvus/Chart.yaml
  charts/milvus/templates/indexnode-deployment.yaml
  charts/milvus/templates/querynode-deployment.yaml
  charts/milvus/templates/standalone-deployment.yaml
  charts/milvus/values.yaml
Labels: lgtm, size/M, approved

#381 Update maxTtDelay in helm
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved
