Repository milvus-io/milvus-helm, pull requests merged in 2022-02, with the labels that each got.

#294 Remove hpa for milvus proxy, query node, index node and data node
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/hpa.yaml
  charts/milvus/values.yaml
Labels: lgtm, approved, size/L

#295 Keep log pvc when release uninstalled
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#296 change env HOST_URL for attu ingress
  charts/milvus/Chart.yaml
  charts/milvus/templates/_helpers.tpl
Labels: size/XS, lgtm, approved

#298 Upgrade pulsar from 2.7.3 to 2.8.2
  charts/milvus/Chart.yaml
  charts/milvus/ci/cluster-values.yaml
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#302 Fix retention duration config
  charts/milvus/Chart.yaml
  charts/milvus/templates/config.tpl
Labels: size/XS, lgtm, approved

#300 Specify the attu image tag
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved
