Repository milvus-io/milvus-helm, pull requests merged in 2022-04, with the labels that each got.

#322 [milvus] Fix issue ingress typo with backend.
  charts/milvus/Chart.yaml
  charts/milvus/templates/attu-ingress.yaml
  charts/milvus/templates/ingress.yaml
Labels: size/XS, lgtm, approved

#324 Bump milvus version to 2.0.2
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#325 Upgrade minio version to RELEASE.2022-03-17T06-34-49Z
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#326 Add default bufFlag config for milvus proxy
  charts/milvus/Chart.yaml
  charts/milvus/templates/config.tpl
Labels: size/XS, lgtm, approved

#315 attu deployment tolerations fix
  charts/milvus/Chart.yaml
  charts/milvus/templates/attu-deployment.yaml
Labels: size/XS, lgtm, approved

#327 Fix duplicate kafka env for MaxMessageBytes
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#332 Add authorization config for milvus
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#333 Add default values for ingress.annotations
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: lgtm, size/M, approved
