Repository milvus-io/milvus-helm, pull requests merged in 2022-01, with the labels that each got.

#282 change configuration for gc
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#284 Increase etcd heartbeat timeout and election timeout
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#285 Add global labels and annotations for for user customization
  charts/milvus/Chart.yaml
  charts/milvus/templates/_helpers.tpl
  charts/milvus/templates/attu-ingress.yaml
  charts/milvus/templates/datacoord-deployment.yaml
  charts/milvus/templates/datanode-deployment.yaml
  charts/milvus/templates/indexcoord-deployment.yaml
  charts/milvus/templates/indexnode-deployment.yaml
  charts/milvus/templates/proxy-deployment.yaml
  charts/milvus/templates/querycoord-deployment.yaml
  charts/milvus/templates/querynode-deployment.yaml
  charts/milvus/templates/rootcoord-deployment.yaml
  charts/milvus/templates/standalone-deployment.yaml
  charts/milvus/values.yaml
Labels: lgtm, size/M, approved

#286 modify pulsar default version
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#287 Downgrade pulsar image version to 2.7.3
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#288 Make the parameter interval of serviceMonitor configurable
  charts/milvus/Chart.yaml
  charts/milvus/templates/servicemonitor.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#290 [milvus] Add default pathType for Ingress.HTTPIngressPath
  charts/milvus/Chart.yaml
  charts/milvus/templates/ingress.yaml
Labels: size/XS, lgtm, approved

#293 Add a configurable parameter scrapeTimeout to serviceMonitor
  charts/milvus/Chart.yaml
  charts/milvus/templates/servicemonitor.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved
