Repository milvus-io/milvus-helm, pull requests merged in 2022-09, with the labels that each got.

#366 [Milvus] Fix version requirement for Attu
  charts/milvus/README.md
Labels: size/XS, lgtm, approved

#365 Add continuous profiling with pyroscope
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/datacoord-deployment.yaml
  charts/milvus/templates/datanode-deployment.yaml
  charts/milvus/templates/indexcoord-deployment.yaml
  charts/milvus/templates/indexnode-deployment.yaml
  charts/milvus/templates/proxy-deployment.yaml
  charts/milvus/templates/querycoord-deployment.yaml
  charts/milvus/templates/querynode-deployment.yaml
  charts/milvus/templates/rootcoord-deployment.yaml
  charts/milvus/templates/standalone-deployment.yaml
  charts/milvus/values.yaml
Labels: lgtm, size/M, approved

#367 Refine kafka default replication factor
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#368 Bump milvus version to v2.1.2
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#369 Upgrade attu image version
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#370 Add quota and limit configs for milvus
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: lgtm, approved, size/L

#371 Bump milvus version to v2.1.3
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: lgtm, size/M, approved

#372 Bump milvus version to v2.1.4
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#373 Add ttl for puslar broker
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#374 Add more config for milvus components
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved
