Repository milvus-io/milvus-helm, pull requests merged in 2022-12, with the labels that each got.

#394 Add dynamic config for milvus
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/config.tpl
  charts/milvus/templates/configmap.yaml
  charts/milvus/templates/datacoord-deployment.yaml
  charts/milvus/templates/datanode-deployment.yaml
  charts/milvus/templates/indexcoord-deployment.yaml
  charts/milvus/templates/indexnode-deployment.yaml
  charts/milvus/templates/proxy-deployment.yaml
  charts/milvus/templates/querycoord-deployment.yaml
  charts/milvus/templates/querynode-deployment.yaml
  charts/milvus/templates/rootcoord-deployment.yaml
  charts/milvus/templates/standalone-deployment.yaml
  charts/milvus/values.yaml
Labels: lgtm, approved, size/L

#396 Add tenant namespace and auth parameters for external pulsar
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#398 Upgrade attu image tag
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#401 Enable pulsar subscription expiration after 30 minutes
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#403 Refine milvus config parameters
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: lgtm, approved, size/XL

#404 Fix milvus config tools for printing config into log
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#406 fix the broken logo
  README.md
Labels: size/XS, lgtm

#407 Bump milvus version to v2.2.2
  charts/milvus/Chart.yaml
  charts/milvus/requirements.lock
  charts/milvus/requirements.yaml
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#408 minio add podmonitor and update metrics path
  charts/minio/Chart.yaml
  charts/minio/templates/podmonitor.yaml
  charts/minio/templates/post-install-prometheus-metrics-job.yaml
  charts/minio/templates/post-install-prometheus-metrics-role.yaml
  charts/minio/templates/post-install-prometheus-metrics-rolebinding.yaml
  charts/minio/templates/post-install-prometheus-metrics-serviceaccount.yaml
  charts/minio/templates/servicemonitor.yaml
  charts/minio/values.yaml
Labels: lgtm, size/M, approved
