Repository milvus-io/milvus-helm, pull requests merged in 2022-03, with the labels that each got.

#306 Upgrade etcd to 3.5.1
  charts/milvus/Chart.yaml
  charts/milvus/charts/etcd-6.13.2.tgz
  charts/milvus/charts/etcd-6.3.3.tgz
  charts/milvus/requirements.lock
  charts/milvus/requirements.yaml
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#309 fix minio chart link
  charts/minio/Chart.yaml
  charts/minio/README.md
Labels: size/XS, lgtm, approved

#312 Downgrade etcd to 3.5.0 due to install issues
  charts/milvus/Chart.yaml
  charts/milvus/charts/etcd-6.13.2.tgz
  charts/milvus/charts/etcd-6.3.3.tgz
  charts/milvus/requirements.lock
  charts/milvus/requirements.yaml
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#317 Fix new pulsar chart release
  .github/workflows/release.yml
  charts/milvus/Chart.yaml
Labels: size/XS, lgtm, approved

#318 Fix pulsar empty port
  charts/milvus/Chart.yaml
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#319 Add kafka for milvus cluster message queue
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/charts/kafka-15.5.1.tgz
  charts/milvus/requirements.lock
  charts/milvus/requirements.yaml
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: lgtm, approved, size/L
