Repository milvus-io/milvus-helm, pull requests merged in 2022-07, with the labels that each got.

#342 Refine kafka deployment
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#343 Use new etcd image to mitigate etcd pod crash
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#344 Add more milvus configs for indexnode and indexcoord
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#346 Fix conflict markers in README.md
  charts/milvus/README.md
Labels: lgtm, size/M, approved

#347 Update attu
  charts/milvus/Chart.yaml
  charts/milvus/templates/_helpers.tpl
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#348 Bump milvus version to v2.1.0
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#349 Add mysql as meta store
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/charts/mysql-9.2.1.tgz
  charts/milvus/requirements.lock
  charts/milvus/requirements.yaml
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: lgtm, approved, size/L

#351 Downgrade mysql version to 8.0.23
  charts/milvus/Chart.yaml
  charts/milvus/charts/mysql-8.5.3.tgz
  charts/milvus/charts/mysql-9.2.1.tgz
  charts/milvus/requirements.lock
  charts/milvus/requirements.yaml
Labels: lgtm, size/S, approved
