Repository milvus-io/milvus-helm, pull requests merged in 2023-02, with the labels that each got.

#417 Refine readme with how to enable log to file
  charts/milvus/README.md
Labels: lgtm, size/S, approved

#418 Bump milvus version to 2.2.3
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#421 Bump attu version to 2.2.3
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#423 Add mergify rules for ci
  .github/mergify.yml
Labels: lgtm, size/M, approved, ci-passed

#424 Remove checkout and release only on tag with version
  .github/workflows/lint-test.yml
  .github/workflows/release.yml
Labels: lgtm, size/S, approved, ci-passed

#427 config ingress' path into values
  charts/milvus/README.md
  charts/milvus/templates/ingress.yaml
  charts/milvus/values.yaml
Labels: lgtm, size/M, approved, ci-passed

#428 add mixcoord
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/_helpers.tpl
  charts/milvus/templates/mixcoord-deployment.yaml
  charts/milvus/templates/mixcoord-svc.yaml
  charts/milvus/values.yaml
Labels: lgtm, approved, size/L, ci-passed
