Repository milvus-io/milvus-helm, pull requests merged in 2023-01, with the labels that each got.

#409 update requirements
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/charts/minio-8.0.14.tgz
  charts/milvus/charts/minio-8.0.15.tgz
  charts/milvus/requirements.lock
  charts/milvus/requirements.yaml
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: lgtm, size/S, approved

#397 Enable active standby for milvus coordinator components
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/config.tpl
  charts/milvus/templates/datacoord-deployment.yaml
  charts/milvus/templates/indexcoord-deployment.yaml
  charts/milvus/templates/querycoord-deployment.yaml
  charts/milvus/templates/rootcoord-deployment.yaml
  charts/milvus/values.yaml
Labels: lgtm, size/M, approved

#412 Update attu version to 2.2.2
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved

#416 Decrease kafka log segment roll duration
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: size/XS, lgtm, approved
